apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sre-microservice-monitor
  namespace: production
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: microservice
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 15s
